FROM elasticsearch:5.6.8-alpine

ENV IK_VER 5.6.8

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v${IK_VER}/elasticsearch-analysis-ik-${IK_VER}.zip

EXPOSE 9200 9300

CMD ["elasticsearch"]

ENTRYPOINT ["/docker-entrypoint.sh"]
